// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ocr.proto
#ifndef GRPC_ocr_2eproto__INCLUDED
#define GRPC_ocr_2eproto__INCLUDED

#include "ocr.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace ocr {

class OCRService final {
 public:
  static constexpr char const* service_full_name() {
    return "ocr.OCRService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::ocr::ImageRequest, ::ocr::OcrResult>> SendImage(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::ocr::ImageRequest, ::ocr::OcrResult>>(SendImageRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ocr::ImageRequest, ::ocr::OcrResult>> AsyncSendImage(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ocr::ImageRequest, ::ocr::OcrResult>>(AsyncSendImageRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ocr::ImageRequest, ::ocr::OcrResult>> PrepareAsyncSendImage(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ocr::ImageRequest, ::ocr::OcrResult>>(PrepareAsyncSendImageRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SendImage(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::ocr::ImageRequest,::ocr::OcrResult>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::ocr::ImageRequest, ::ocr::OcrResult>* SendImageRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::ocr::ImageRequest, ::ocr::OcrResult>* AsyncSendImageRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::ocr::ImageRequest, ::ocr::OcrResult>* PrepareAsyncSendImageRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::ocr::ImageRequest, ::ocr::OcrResult>> SendImage(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::ocr::ImageRequest, ::ocr::OcrResult>>(SendImageRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::ocr::ImageRequest, ::ocr::OcrResult>> AsyncSendImage(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::ocr::ImageRequest, ::ocr::OcrResult>>(AsyncSendImageRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::ocr::ImageRequest, ::ocr::OcrResult>> PrepareAsyncSendImage(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::ocr::ImageRequest, ::ocr::OcrResult>>(PrepareAsyncSendImageRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendImage(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::ocr::ImageRequest,::ocr::OcrResult>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::ocr::ImageRequest, ::ocr::OcrResult>* SendImageRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::ocr::ImageRequest, ::ocr::OcrResult>* AsyncSendImageRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::ocr::ImageRequest, ::ocr::OcrResult>* PrepareAsyncSendImageRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendImage_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendImage(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::ocr::OcrResult, ::ocr::ImageRequest>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendImage() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendImage(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ocr::OcrResult, ::ocr::ImageRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendImage(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::ocr::OcrResult, ::ocr::ImageRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendImage<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendImage() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::ocr::ImageRequest, ::ocr::OcrResult>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->SendImage(context); }));
    }
    ~WithCallbackMethod_SendImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendImage(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ocr::OcrResult, ::ocr::ImageRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::ocr::ImageRequest, ::ocr::OcrResult>* SendImage(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_SendImage<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendImage() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendImage(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ocr::OcrResult, ::ocr::ImageRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendImage() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendImage(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ocr::OcrResult, ::ocr::ImageRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendImage(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendImage() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->SendImage(context); }));
    }
    ~WithRawCallbackMethod_SendImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendImage(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ocr::OcrResult, ::ocr::ImageRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* SendImage(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace ocr


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_ocr_2eproto__INCLUDED
