// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ocr.proto

#include "ocr.pb.h"
#include "ocr.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ocr {

static const char* OCRService_method_names[] = {
  "/ocr.OCRService/SendImage",
};

std::unique_ptr< OCRService::Stub> OCRService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< OCRService::Stub> stub(new OCRService::Stub(channel, options));
  return stub;
}

OCRService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendImage_(OCRService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::ocr::ImageRequest, ::ocr::OcrResult>* OCRService::Stub::SendImageRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::ocr::ImageRequest, ::ocr::OcrResult>::Create(channel_.get(), rpcmethod_SendImage_, context);
}

void OCRService::Stub::async::SendImage(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::ocr::ImageRequest,::ocr::OcrResult>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::ocr::ImageRequest,::ocr::OcrResult>::Create(stub_->channel_.get(), stub_->rpcmethod_SendImage_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::ocr::ImageRequest, ::ocr::OcrResult>* OCRService::Stub::AsyncSendImageRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::ocr::ImageRequest, ::ocr::OcrResult>::Create(channel_.get(), cq, rpcmethod_SendImage_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::ocr::ImageRequest, ::ocr::OcrResult>* OCRService::Stub::PrepareAsyncSendImageRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::ocr::ImageRequest, ::ocr::OcrResult>::Create(channel_.get(), cq, rpcmethod_SendImage_, context, false, nullptr);
}

OCRService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OCRService_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< OCRService::Service, ::ocr::ImageRequest, ::ocr::OcrResult>(
          [](OCRService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::ocr::OcrResult,
             ::ocr::ImageRequest>* stream) {
               return service->SendImage(ctx, stream);
             }, this)));
}

OCRService::Service::~Service() {
}

::grpc::Status OCRService::Service::SendImage(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::ocr::OcrResult, ::ocr::ImageRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ocr

