// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ocr.proto
// Protobuf C++ Version: 5.29.5

#include "ocr.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace ocr {

inline constexpr OcrResult::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : batch_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        image_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        text_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR OcrResult::OcrResult(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct OcrResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OcrResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~OcrResultDefaultTypeInternal() {}
  union {
    OcrResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OcrResultDefaultTypeInternal _OcrResult_default_instance_;

inline constexpr ImageRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : batch_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        image_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ImageRequest::ImageRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ImageRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ImageRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ImageRequestDefaultTypeInternal() {}
  union {
    ImageRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ImageRequestDefaultTypeInternal _ImageRequest_default_instance_;
}  // namespace ocr
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_ocr_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ocr_2eproto = nullptr;
const ::uint32_t
    TableStruct_ocr_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::ocr::ImageRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ocr::ImageRequest, _impl_.batch_id_),
        PROTOBUF_FIELD_OFFSET(::ocr::ImageRequest, _impl_.image_id_),
        PROTOBUF_FIELD_OFFSET(::ocr::ImageRequest, _impl_.data_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::ocr::OcrResult, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ocr::OcrResult, _impl_.batch_id_),
        PROTOBUF_FIELD_OFFSET(::ocr::OcrResult, _impl_.image_id_),
        PROTOBUF_FIELD_OFFSET(::ocr::OcrResult, _impl_.text_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::ocr::ImageRequest)},
        {11, -1, -1, sizeof(::ocr::OcrResult)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::ocr::_ImageRequest_default_instance_._instance,
    &::ocr::_OcrResult_default_instance_._instance,
};
const char descriptor_table_protodef_ocr_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\tocr.proto\022\003ocr\"@\n\014ImageRequest\022\020\n\010batc"
    "h_id\030\001 \001(\t\022\020\n\010image_id\030\002 \001(\t\022\014\n\004data\030\003 \001"
    "(\014\"=\n\tOcrResult\022\020\n\010batch_id\030\001 \001(\t\022\020\n\010ima"
    "ge_id\030\002 \001(\t\022\014\n\004text\030\003 \001(\t2@\n\nOCRService\022"
    "2\n\tSendImage\022\021.ocr.ImageRequest\032\016.ocr.Oc"
    "rResult(\0010\001b\006proto3"
};
static ::absl::once_flag descriptor_table_ocr_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ocr_2eproto = {
    false,
    false,
    219,
    descriptor_table_protodef_ocr_2eproto,
    "ocr.proto",
    &descriptor_table_ocr_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_ocr_2eproto::offsets,
    file_level_enum_descriptors_ocr_2eproto,
    file_level_service_descriptors_ocr_2eproto,
};
namespace ocr {
// ===================================================================

class ImageRequest::_Internal {
 public:
};

ImageRequest::ImageRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ocr.ImageRequest)
}
inline PROTOBUF_NDEBUG_INLINE ImageRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::ocr::ImageRequest& from_msg)
      : batch_id_(arena, from.batch_id_),
        image_id_(arena, from.image_id_),
        data_(arena, from.data_),
        _cached_size_{0} {}

ImageRequest::ImageRequest(
    ::google::protobuf::Arena* arena,
    const ImageRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ImageRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:ocr.ImageRequest)
}
inline PROTOBUF_NDEBUG_INLINE ImageRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : batch_id_(arena),
        image_id_(arena),
        data_(arena),
        _cached_size_{0} {}

inline void ImageRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ImageRequest::~ImageRequest() {
  // @@protoc_insertion_point(destructor:ocr.ImageRequest)
  SharedDtor(*this);
}
inline void ImageRequest::SharedDtor(MessageLite& self) {
  ImageRequest& this_ = static_cast<ImageRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.batch_id_.Destroy();
  this_._impl_.image_id_.Destroy();
  this_._impl_.data_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ImageRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ImageRequest(arena);
}
constexpr auto ImageRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ImageRequest),
                                            alignof(ImageRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ImageRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ImageRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ImageRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ImageRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ImageRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ImageRequest>(), &ImageRequest::ByteSizeLong,
            &ImageRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ImageRequest, _impl_._cached_size_),
        false,
    },
    &ImageRequest::kDescriptorMethods,
    &descriptor_table_ocr_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ImageRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 41, 2> ImageRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ocr::ImageRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string batch_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ImageRequest, _impl_.batch_id_)}},
    // string image_id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ImageRequest, _impl_.image_id_)}},
    // bytes data = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(ImageRequest, _impl_.data_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string batch_id = 1;
    {PROTOBUF_FIELD_OFFSET(ImageRequest, _impl_.batch_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string image_id = 2;
    {PROTOBUF_FIELD_OFFSET(ImageRequest, _impl_.image_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes data = 3;
    {PROTOBUF_FIELD_OFFSET(ImageRequest, _impl_.data_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\20\10\10\0\0\0\0\0"
    "ocr.ImageRequest"
    "batch_id"
    "image_id"
  }},
};

PROTOBUF_NOINLINE void ImageRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:ocr.ImageRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.batch_id_.ClearToEmpty();
  _impl_.image_id_.ClearToEmpty();
  _impl_.data_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ImageRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ImageRequest& this_ = static_cast<const ImageRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ImageRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ImageRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:ocr.ImageRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string batch_id = 1;
          if (!this_._internal_batch_id().empty()) {
            const std::string& _s = this_._internal_batch_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ocr.ImageRequest.batch_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string image_id = 2;
          if (!this_._internal_image_id().empty()) {
            const std::string& _s = this_._internal_image_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ocr.ImageRequest.image_id");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // bytes data = 3;
          if (!this_._internal_data().empty()) {
            const std::string& _s = this_._internal_data();
            target = stream->WriteBytesMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:ocr.ImageRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ImageRequest::ByteSizeLong(const MessageLite& base) {
          const ImageRequest& this_ = static_cast<const ImageRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ImageRequest::ByteSizeLong() const {
          const ImageRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:ocr.ImageRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string batch_id = 1;
            if (!this_._internal_batch_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_batch_id());
            }
            // string image_id = 2;
            if (!this_._internal_image_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_image_id());
            }
            // bytes data = 3;
            if (!this_._internal_data().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_data());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ImageRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ImageRequest*>(&to_msg);
  auto& from = static_cast<const ImageRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ocr.ImageRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_batch_id().empty()) {
    _this->_internal_set_batch_id(from._internal_batch_id());
  }
  if (!from._internal_image_id().empty()) {
    _this->_internal_set_image_id(from._internal_image_id());
  }
  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ImageRequest::CopyFrom(const ImageRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ocr.ImageRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ImageRequest::InternalSwap(ImageRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.batch_id_, &other->_impl_.batch_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.image_id_, &other->_impl_.image_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
}

::google::protobuf::Metadata ImageRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class OcrResult::_Internal {
 public:
};

OcrResult::OcrResult(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ocr.OcrResult)
}
inline PROTOBUF_NDEBUG_INLINE OcrResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::ocr::OcrResult& from_msg)
      : batch_id_(arena, from.batch_id_),
        image_id_(arena, from.image_id_),
        text_(arena, from.text_),
        _cached_size_{0} {}

OcrResult::OcrResult(
    ::google::protobuf::Arena* arena,
    const OcrResult& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  OcrResult* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:ocr.OcrResult)
}
inline PROTOBUF_NDEBUG_INLINE OcrResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : batch_id_(arena),
        image_id_(arena),
        text_(arena),
        _cached_size_{0} {}

inline void OcrResult::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
OcrResult::~OcrResult() {
  // @@protoc_insertion_point(destructor:ocr.OcrResult)
  SharedDtor(*this);
}
inline void OcrResult::SharedDtor(MessageLite& self) {
  OcrResult& this_ = static_cast<OcrResult&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.batch_id_.Destroy();
  this_._impl_.image_id_.Destroy();
  this_._impl_.text_.Destroy();
  this_._impl_.~Impl_();
}

inline void* OcrResult::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) OcrResult(arena);
}
constexpr auto OcrResult::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(OcrResult),
                                            alignof(OcrResult));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull OcrResult::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_OcrResult_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &OcrResult::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<OcrResult>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &OcrResult::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<OcrResult>(), &OcrResult::ByteSizeLong,
            &OcrResult::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(OcrResult, _impl_._cached_size_),
        false,
    },
    &OcrResult::kDescriptorMethods,
    &descriptor_table_ocr_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* OcrResult::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 42, 2> OcrResult::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ocr::OcrResult>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string batch_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(OcrResult, _impl_.batch_id_)}},
    // string image_id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(OcrResult, _impl_.image_id_)}},
    // string text = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(OcrResult, _impl_.text_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string batch_id = 1;
    {PROTOBUF_FIELD_OFFSET(OcrResult, _impl_.batch_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string image_id = 2;
    {PROTOBUF_FIELD_OFFSET(OcrResult, _impl_.image_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string text = 3;
    {PROTOBUF_FIELD_OFFSET(OcrResult, _impl_.text_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\15\10\10\4\0\0\0\0"
    "ocr.OcrResult"
    "batch_id"
    "image_id"
    "text"
  }},
};

PROTOBUF_NOINLINE void OcrResult::Clear() {
// @@protoc_insertion_point(message_clear_start:ocr.OcrResult)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.batch_id_.ClearToEmpty();
  _impl_.image_id_.ClearToEmpty();
  _impl_.text_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* OcrResult::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const OcrResult& this_ = static_cast<const OcrResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* OcrResult::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const OcrResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:ocr.OcrResult)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string batch_id = 1;
          if (!this_._internal_batch_id().empty()) {
            const std::string& _s = this_._internal_batch_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ocr.OcrResult.batch_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string image_id = 2;
          if (!this_._internal_image_id().empty()) {
            const std::string& _s = this_._internal_image_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ocr.OcrResult.image_id");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string text = 3;
          if (!this_._internal_text().empty()) {
            const std::string& _s = this_._internal_text();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ocr.OcrResult.text");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:ocr.OcrResult)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t OcrResult::ByteSizeLong(const MessageLite& base) {
          const OcrResult& this_ = static_cast<const OcrResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t OcrResult::ByteSizeLong() const {
          const OcrResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:ocr.OcrResult)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string batch_id = 1;
            if (!this_._internal_batch_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_batch_id());
            }
            // string image_id = 2;
            if (!this_._internal_image_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_image_id());
            }
            // string text = 3;
            if (!this_._internal_text().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_text());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void OcrResult::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<OcrResult*>(&to_msg);
  auto& from = static_cast<const OcrResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ocr.OcrResult)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_batch_id().empty()) {
    _this->_internal_set_batch_id(from._internal_batch_id());
  }
  if (!from._internal_image_id().empty()) {
    _this->_internal_set_image_id(from._internal_image_id());
  }
  if (!from._internal_text().empty()) {
    _this->_internal_set_text(from._internal_text());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void OcrResult::CopyFrom(const OcrResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ocr.OcrResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void OcrResult::InternalSwap(OcrResult* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.batch_id_, &other->_impl_.batch_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.image_id_, &other->_impl_.image_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.text_, &other->_impl_.text_, arena);
}

::google::protobuf::Metadata OcrResult::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace ocr
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_ocr_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
