// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ocr.proto
// Protobuf C++ Version: 5.29.5

#ifndef ocr_2eproto_2epb_2eh
#define ocr_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ocr_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ocr_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ocr_2eproto;
namespace ocr {
class ImageRequest;
struct ImageRequestDefaultTypeInternal;
extern ImageRequestDefaultTypeInternal _ImageRequest_default_instance_;
class OcrResult;
struct OcrResultDefaultTypeInternal;
extern OcrResultDefaultTypeInternal _OcrResult_default_instance_;
}  // namespace ocr
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace ocr {

// ===================================================================


// -------------------------------------------------------------------

class OcrResult final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ocr.OcrResult) */ {
 public:
  inline OcrResult() : OcrResult(nullptr) {}
  ~OcrResult() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(OcrResult* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(OcrResult));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR OcrResult(
      ::google::protobuf::internal::ConstantInitialized);

  inline OcrResult(const OcrResult& from) : OcrResult(nullptr, from) {}
  inline OcrResult(OcrResult&& from) noexcept
      : OcrResult(nullptr, std::move(from)) {}
  inline OcrResult& operator=(const OcrResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline OcrResult& operator=(OcrResult&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OcrResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const OcrResult* internal_default_instance() {
    return reinterpret_cast<const OcrResult*>(
        &_OcrResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(OcrResult& a, OcrResult& b) { a.Swap(&b); }
  inline void Swap(OcrResult* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OcrResult* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OcrResult* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<OcrResult>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const OcrResult& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const OcrResult& from) { OcrResult::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(OcrResult* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ocr.OcrResult"; }

 protected:
  explicit OcrResult(::google::protobuf::Arena* arena);
  OcrResult(::google::protobuf::Arena* arena, const OcrResult& from);
  OcrResult(::google::protobuf::Arena* arena, OcrResult&& from) noexcept
      : OcrResult(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBatchIdFieldNumber = 1,
    kImageIdFieldNumber = 2,
    kTextFieldNumber = 3,
  };
  // string batch_id = 1;
  void clear_batch_id() ;
  const std::string& batch_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_batch_id(Arg_&& arg, Args_... args);
  std::string* mutable_batch_id();
  PROTOBUF_NODISCARD std::string* release_batch_id();
  void set_allocated_batch_id(std::string* value);

  private:
  const std::string& _internal_batch_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_batch_id(
      const std::string& value);
  std::string* _internal_mutable_batch_id();

  public:
  // string image_id = 2;
  void clear_image_id() ;
  const std::string& image_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_image_id(Arg_&& arg, Args_... args);
  std::string* mutable_image_id();
  PROTOBUF_NODISCARD std::string* release_image_id();
  void set_allocated_image_id(std::string* value);

  private:
  const std::string& _internal_image_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_image_id(
      const std::string& value);
  std::string* _internal_mutable_image_id();

  public:
  // string text = 3;
  void clear_text() ;
  const std::string& text() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_text(Arg_&& arg, Args_... args);
  std::string* mutable_text();
  PROTOBUF_NODISCARD std::string* release_text();
  void set_allocated_text(std::string* value);

  private:
  const std::string& _internal_text() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_text(
      const std::string& value);
  std::string* _internal_mutable_text();

  public:
  // @@protoc_insertion_point(class_scope:ocr.OcrResult)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      42, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const OcrResult& from_msg);
    ::google::protobuf::internal::ArenaStringPtr batch_id_;
    ::google::protobuf::internal::ArenaStringPtr image_id_;
    ::google::protobuf::internal::ArenaStringPtr text_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ocr_2eproto;
};
// -------------------------------------------------------------------

class ImageRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ocr.ImageRequest) */ {
 public:
  inline ImageRequest() : ImageRequest(nullptr) {}
  ~ImageRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ImageRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ImageRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ImageRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline ImageRequest(const ImageRequest& from) : ImageRequest(nullptr, from) {}
  inline ImageRequest(ImageRequest&& from) noexcept
      : ImageRequest(nullptr, std::move(from)) {}
  inline ImageRequest& operator=(const ImageRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ImageRequest& operator=(ImageRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ImageRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ImageRequest* internal_default_instance() {
    return reinterpret_cast<const ImageRequest*>(
        &_ImageRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ImageRequest& a, ImageRequest& b) { a.Swap(&b); }
  inline void Swap(ImageRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ImageRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ImageRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ImageRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ImageRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ImageRequest& from) { ImageRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ImageRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ocr.ImageRequest"; }

 protected:
  explicit ImageRequest(::google::protobuf::Arena* arena);
  ImageRequest(::google::protobuf::Arena* arena, const ImageRequest& from);
  ImageRequest(::google::protobuf::Arena* arena, ImageRequest&& from) noexcept
      : ImageRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBatchIdFieldNumber = 1,
    kImageIdFieldNumber = 2,
    kDataFieldNumber = 3,
  };
  // string batch_id = 1;
  void clear_batch_id() ;
  const std::string& batch_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_batch_id(Arg_&& arg, Args_... args);
  std::string* mutable_batch_id();
  PROTOBUF_NODISCARD std::string* release_batch_id();
  void set_allocated_batch_id(std::string* value);

  private:
  const std::string& _internal_batch_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_batch_id(
      const std::string& value);
  std::string* _internal_mutable_batch_id();

  public:
  // string image_id = 2;
  void clear_image_id() ;
  const std::string& image_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_image_id(Arg_&& arg, Args_... args);
  std::string* mutable_image_id();
  PROTOBUF_NODISCARD std::string* release_image_id();
  void set_allocated_image_id(std::string* value);

  private:
  const std::string& _internal_image_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_image_id(
      const std::string& value);
  std::string* _internal_mutable_image_id();

  public:
  // bytes data = 3;
  void clear_data() ;
  const std::string& data() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* value);

  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(
      const std::string& value);
  std::string* _internal_mutable_data();

  public:
  // @@protoc_insertion_point(class_scope:ocr.ImageRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      41, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ImageRequest& from_msg);
    ::google::protobuf::internal::ArenaStringPtr batch_id_;
    ::google::protobuf::internal::ArenaStringPtr image_id_;
    ::google::protobuf::internal::ArenaStringPtr data_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ocr_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ImageRequest

// string batch_id = 1;
inline void ImageRequest::clear_batch_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.batch_id_.ClearToEmpty();
}
inline const std::string& ImageRequest::batch_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ocr.ImageRequest.batch_id)
  return _internal_batch_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ImageRequest::set_batch_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.batch_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ocr.ImageRequest.batch_id)
}
inline std::string* ImageRequest::mutable_batch_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_batch_id();
  // @@protoc_insertion_point(field_mutable:ocr.ImageRequest.batch_id)
  return _s;
}
inline const std::string& ImageRequest::_internal_batch_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.batch_id_.Get();
}
inline void ImageRequest::_internal_set_batch_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.batch_id_.Set(value, GetArena());
}
inline std::string* ImageRequest::_internal_mutable_batch_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.batch_id_.Mutable( GetArena());
}
inline std::string* ImageRequest::release_batch_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ocr.ImageRequest.batch_id)
  return _impl_.batch_id_.Release();
}
inline void ImageRequest::set_allocated_batch_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.batch_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.batch_id_.IsDefault()) {
    _impl_.batch_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ocr.ImageRequest.batch_id)
}

// string image_id = 2;
inline void ImageRequest::clear_image_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_id_.ClearToEmpty();
}
inline const std::string& ImageRequest::image_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ocr.ImageRequest.image_id)
  return _internal_image_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ImageRequest::set_image_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ocr.ImageRequest.image_id)
}
inline std::string* ImageRequest::mutable_image_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_image_id();
  // @@protoc_insertion_point(field_mutable:ocr.ImageRequest.image_id)
  return _s;
}
inline const std::string& ImageRequest::_internal_image_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.image_id_.Get();
}
inline void ImageRequest::_internal_set_image_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_id_.Set(value, GetArena());
}
inline std::string* ImageRequest::_internal_mutable_image_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.image_id_.Mutable( GetArena());
}
inline std::string* ImageRequest::release_image_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ocr.ImageRequest.image_id)
  return _impl_.image_id_.Release();
}
inline void ImageRequest::set_allocated_image_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.image_id_.IsDefault()) {
    _impl_.image_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ocr.ImageRequest.image_id)
}

// bytes data = 3;
inline void ImageRequest::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
}
inline const std::string& ImageRequest::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ocr.ImageRequest.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ImageRequest::set_data(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ocr.ImageRequest.data)
}
inline std::string* ImageRequest::mutable_data() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:ocr.ImageRequest.data)
  return _s;
}
inline const std::string& ImageRequest::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void ImageRequest::_internal_set_data(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline std::string* ImageRequest::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline std::string* ImageRequest::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ocr.ImageRequest.data)
  return _impl_.data_.Release();
}
inline void ImageRequest::set_allocated_data(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ocr.ImageRequest.data)
}

// -------------------------------------------------------------------

// OcrResult

// string batch_id = 1;
inline void OcrResult::clear_batch_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.batch_id_.ClearToEmpty();
}
inline const std::string& OcrResult::batch_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ocr.OcrResult.batch_id)
  return _internal_batch_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void OcrResult::set_batch_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.batch_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ocr.OcrResult.batch_id)
}
inline std::string* OcrResult::mutable_batch_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_batch_id();
  // @@protoc_insertion_point(field_mutable:ocr.OcrResult.batch_id)
  return _s;
}
inline const std::string& OcrResult::_internal_batch_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.batch_id_.Get();
}
inline void OcrResult::_internal_set_batch_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.batch_id_.Set(value, GetArena());
}
inline std::string* OcrResult::_internal_mutable_batch_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.batch_id_.Mutable( GetArena());
}
inline std::string* OcrResult::release_batch_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ocr.OcrResult.batch_id)
  return _impl_.batch_id_.Release();
}
inline void OcrResult::set_allocated_batch_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.batch_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.batch_id_.IsDefault()) {
    _impl_.batch_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ocr.OcrResult.batch_id)
}

// string image_id = 2;
inline void OcrResult::clear_image_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_id_.ClearToEmpty();
}
inline const std::string& OcrResult::image_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ocr.OcrResult.image_id)
  return _internal_image_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void OcrResult::set_image_id(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ocr.OcrResult.image_id)
}
inline std::string* OcrResult::mutable_image_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_image_id();
  // @@protoc_insertion_point(field_mutable:ocr.OcrResult.image_id)
  return _s;
}
inline const std::string& OcrResult::_internal_image_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.image_id_.Get();
}
inline void OcrResult::_internal_set_image_id(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_id_.Set(value, GetArena());
}
inline std::string* OcrResult::_internal_mutable_image_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.image_id_.Mutable( GetArena());
}
inline std::string* OcrResult::release_image_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ocr.OcrResult.image_id)
  return _impl_.image_id_.Release();
}
inline void OcrResult::set_allocated_image_id(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.image_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.image_id_.IsDefault()) {
    _impl_.image_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ocr.OcrResult.image_id)
}

// string text = 3;
inline void OcrResult::clear_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.text_.ClearToEmpty();
}
inline const std::string& OcrResult::text() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ocr.OcrResult.text)
  return _internal_text();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void OcrResult::set_text(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.text_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ocr.OcrResult.text)
}
inline std::string* OcrResult::mutable_text() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_text();
  // @@protoc_insertion_point(field_mutable:ocr.OcrResult.text)
  return _s;
}
inline const std::string& OcrResult::_internal_text() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.text_.Get();
}
inline void OcrResult::_internal_set_text(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.text_.Set(value, GetArena());
}
inline std::string* OcrResult::_internal_mutable_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.text_.Mutable( GetArena());
}
inline std::string* OcrResult::release_text() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ocr.OcrResult.text)
  return _impl_.text_.Release();
}
inline void OcrResult::set_allocated_text(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.text_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.text_.IsDefault()) {
    _impl_.text_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ocr.OcrResult.text)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace ocr


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ocr_2eproto_2epb_2eh
